version: 2
jobs:
  build:
    docker: 
      - image: circleci/openjdk:stretch
    environment:
      MAVEN_OPTS: -Xmx6400m
    steps:
      # Checkout the source code
      # ########################
      - checkout

      # Restore any files we may have cached
      # ########################
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # Download maven dependencies so that we can cache them
      # ########################
      - run:
          name: Download Dependencies
          command: mvn dependency:go-offline
      # Cache the maven dependencies
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: Checking known OWASP vulnerabilities
          command: mvn verify -Dcheckstyle.skip -DskipUTs -DskipPTs -DskipFTs
      - run:
          name: Verifying dependencies updates
          command: mvn versions:display-dependency-updates
      - run:
          name: Checking plugin updates
          command: mvn versions:display-plugin-updates
      - run:
          name: Verifying checkstyle 
          command: mvn validate 
      - run:
          name: Unit tests
          command: mvn test -DskipDCs -Dcheckstyle.skip -DskipFTs -DskipPTs
      - run:
          name: Functional Tests
          command: mvn verify  -DskipDCs -Dcheckstyle.skip -DskipUTs -DskipPTs
