apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devops-test
  name: devops-test
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  replicas: 3
  selector:
    matchLabels:
      app: devops-test
  template:
    metadata:
      labels:
        app: devops-test
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: someimage:latest
          imagePullPolicy: Always
          name: devops-test
          ports:
            - containerPort: 80